baseurl = "https://tinker-oscar-42786.netlify.com"
languageCode = "en-us"
languageLang = "en"
title = "AIRahimi"
author = "Hamid Rahimi"
canonifyurls = true
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

[[redirects]]
from = "/netlify/*"
to = "https://www.google.com:443/search?q=%3Asplat"
status = 301
force = true

[params]
	colorScheme = "scheme-lightbrown"
	DateFormat = "15:04 - 2 Januar, 06"
	description = "Blog for Netlify application"
	sidebarDescription = ""
	sidebarFreeText = ""
	copyright = "Hamid Rahimi © 2017. All rights reserved"
	piwikSiteID = ""
	piwikURL = ""
	
[[menu.main]]
	name = "Posts"
	url = "/posts/"
	weight = 1

[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2

[[menu.main]]
	name = "Netlify"
	url = "http://netlify.com"
	weight = 3



